### ISSUE TITLE
部分nai3图片无法解析

### ISSUE THREAD

**Issue by chairdan** [Akegarasu/stable-diffusion-inspector#12]
图片案例，来源pixiv https://www.pixiv.net/artworks/116997657
nai3网页可读取
![image](https://github.com/Akegarasu/stable-diffusion-inspector/assets/81518985/da189985-6e32-4c52-9f70-dd9ea55e9f29)
![image](https://github.com/Akegarasu/stable-diffusion-inspector/assets/81518985/060ec524-3113-480d-88eb-201869104433)

**Comment by Akegarasu** [comment]
fixed
