### ISSUE TITLE
大佬这个项目如何搭建？可以出个搭建说明不？

### ISSUE THREAD

**Issue by kbc1118** [Akegarasu/stable-diffusion-inspector#16]
大佬这个项目如何搭建？可以出个搭建说明不？
想搭建在debian系统上自己用

**Comment by Exception0x0194** [comment]
It's very easy to build (and locally host) a page developed in Vue:

1. Clone the repo
    ```bash
    git clone https://github.com/Akegarasu/stable-diffusion-inspector
    
    cd stable-diffusion-inspector
    ```

2. Install npm dependencies and build pages
    ```bash
    npm i
    
    npm run build
    ````

3. Host the server (in this case we are using python's http package to host the pages locally)
    ```bash
    python -m http.server -d dist 10801
    ```

Though the steps you should find the webpage available on [127.0.0.1:10801](http://localhost:10801/).
