### ISSUE TITLE
考虑部署到netlify？

### ISSUE THREAD

**Issue by riife** [Akegarasu/stable-diffusion-inspector#2]
如题，vercel.app子域名无法直接访问

**Comment by Akegarasu** [comment]
还不如vercel

**Comment by Akegarasu** [comment]
emmmm 我不知道是我的还是你的结果有问题
![image](https://user-images.githubusercontent.com/36563862/197371129-2a259db2-cb87-453f-8f5a-bcddeb555a15.png)
![image](https://user-images.githubusercontent.com/36563862/197371134-83eb17a0-1082-4163-a1a1-71adec2f2bb7.png)
